name: Publish package to GitHub Packages
on:
  release:
    types: [created]
  pull_request:
    branches: [main]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 8.0.232
          server-id: github-packages # Value of the distributionManagement/repository/id field of the pom.xml
          server-username: pmanko
          server-password: ${{ secrets.TOKEN }} # env variable for token in deploy
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4
        with:
          maven-version: 3.6.3
#      - name: Cache Maven packages
#        uses: actions/cache@v2
#        with:
#          path: ~/.m2
#          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
#          restore-keys: ${{ runner.os }}-m2
      - uses: s4u/maven-settings-action@v2.2.0
        with:
          servers: |
            [{
                "id": "github-packages",
                "username": "${{ secrets.RELEASE_USERNAME }}",
                "password": "${{ secrets.RELEASE_TOKEN }}"
            }]
          properties: |
            [
              { "maven.wagon.http.ssl.insecure": "true" },
              { "maven.wagon.http.ssl.allowall": "true" },
              { "maven.wagon.http.ssl.ignore.validity.dates": "true"}
            ]
          githubServer: false
      - name: Build
        run: mvn -P github-packages -DskipTests -B package
      - name: Publish package
        run: mvn -P github-packages -DskipTests -B deploy
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
